# Generated by Django 5.1.2 on 2024-11-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_useraddresses_user_alter_userorders_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.BigIntegerField(default=9999999999, unique=True),
        ),
    ]
