# Generated by Django 5.1.2 on 2024-11-03 20:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_address_house_no_alter_userprofile_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=ckeditor.fields.RichTextField(default='No description available'),
        ),
    ]
